app = "gun-relay-3dvr"

[env]
PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 50

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
