app = "gun-relay-3dvr"

[env]
PORT = "8765"

[[services]]
  internal_port = 8765
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 50

  [[services.ports]]
    port = 80
  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
